config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'main#index'
  get '/posts' => 'main#index', as: :posts
  get '/posts/:id' => "main#show", as: :post
  get '/post/new' => "main#new", as: :new
  post '/post' => "main#create"

  get '/update/:id' => "main#update", as: :update
  patch '/update/:id' => "main#update_post"

  delete '/posts/:id' => "main#delete", as: :delete


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    @posts = Post.all.sort { |a, b| a.created_at - b.created_at }
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    # render 'new.html.erb'
  end

  def create
    @post = Post.create(
		title: params[:title],
		content: params[:content]
	)
	if @post.valid?
		redirect_to @post
	else
		render action: :new
	end

  end

  def delete
	  @post = Post.find(params[:id]).destroy
	  redirect_to '/'
  end

  def update
	@post = Post.find(params[:id])
	@title = @post.title.split(' ').join('_')
	@content = @post.content
  end

  def update_post
	  byebug
	  @post = Post.update(params[:id], title: params[:title], content: params[:content])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Check, check, one, two...</h1>

<ul>
<% @posts.each do |post| %>
<li>
  <%= link_to post.title, post %>
</li>
<% end %>
</ul>
<h6><%= link_to "Write your own post!", :new %></h6>

app/views/main/new.html.erb
<h1>Sit down and WRITE a blog post NOW</h1>

<%= form_with url: "/post", local: true do %>

	<label for="title">Title</label>
	<input type="text" name="title" minlength='1' maxlength ='100' required />
	<br />
	<label for="content">Stuff Goes Here!</label>
	<textarea type="text" name="content" style="height: 40px; width: 200px" minlength='1' maxlength ='400' required ></textarea>
	<br />
	<input type="submit" value="Post it, baby!">


<% end %>

<br />
<h6><%= link_to "Back to Posts", :posts %></h6>

app/views/main/show.html.erb
<h3><%= @post.title %></h3>
<p><%= @post.content %></p>

<h6><%= link_to "update this post", "/update/#{@post.id}" %></h6>
<%= button_to 'button version of delete', delete_path, method: :delete %>

<h6><%= link_to "Back to Posts", :posts %></h6>

app/views/main/update.html.erb
<h1>Update Existing Post</h1>

<%= form_with url: "/update/#{@post.id}", local: true, method: :patch do %>

	<label for="title">Title</label>
	<input type="text" name="title"
	 value=<%= @title %>
	 minlength='1' maxlength ='100' required />
	<br />
	<label for="content">Stuff Goes Here!</label>
	<textarea type="text" name="content" value=<%= @content %> style="height: 40px; width: 200px" minlength='1' maxlength ='400' required ></textarea>
	<br />
	<input type="submit" value="Patch it, baby!">


<% end %>

<br />
<h6><%= link_to "Back to Posts", :posts %></h6>